export const shoes = [
  {
    id: '1',
    name: 'baby shoes',
    size: '22',
    price: '45',
    image: '/images/baby_shoes.jpg',
  },
  {
    id: '2',
    name: 'hiking_shoes',
    size: '43',
    price: '65',
    image: '/images/hiking_shoes.jpg',
  },
  {
    id: '3',
    name: 'pumps_black',
    size: '41',
    price: '27',
    image: '/images/pumps_black.jpg',
  },
  {
    id: '4',
    name: 'pumps_pink',
    size: '40',
    price: '119',
    image: '/images/pumps_pink.jpg',
  },
  {
    id: '5',
    name: 'pumps_red',
    size: '37',
    price: '580',
    image: '/images/pumps_red.jpg',
  },
  {
    id: '6',
    name: 'sneaker_pink',
    size: '40',
    price: '19',
    image: '/images/sneaker_pink.jpg',
  },
  {
    id: '7',
    name: 'sneaker_superhero',
    size: '44',
    price: '99',
    image: '/images/sneaker_superhero.jpg',
  },
  {
    id: '8',
    name: 'sneaker_white',
    size: '43',
    price: '15',
    image: '/images/sneaker_white.jpg',
  },
  {
    id: '9',
    name: 'wedges_brown',
    size: '37',
    price: '23',
    image: '/images/wedges_brown.jpg',
  },
];
